config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  resources :users
  resources :products
  namespace :admin do
    resources :products do
      resources :prices
    end
    resources :brands
    resources :categories
  end

  # post 'admin/products/:id', to: 'admin/products#create'

  get 'admin', to: 'admin#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#logout'
  get 'permission_restriction', to: 'sessions#permission_restriction'

  get 'admin/login', to: 'admin#login'
  post 'admin/login', to: 'admin#login_auth'
  post 'admin/logout', to: 'admin#logout'
end

app/models/price.rb
class Price < ApplicationRecord
  # validates :price, format: { with: /\d*/, message: "only allows numbers" }
  validates :price, presence: true, format: {with: /\d+/, message: 'only allows numbers'}
  validates :seller, presence: true
  validates :link, presence: true, format: {with: %r{\A(http|https)://}, message: 'Link format should start with http/https'}
  before_save :price_format

  def price_format
    self.price = if self.price_was.nil?
                   [{updated_at: Time.now, price: price}]
                 else
                   self.price_was + [{updated_at: Time.now, price: price}]
                 end
  end
end

app/controllers/admin/prices_controller.rb
class Admin::PricesController < ApplicationController
  before_action :product
  before_action :price, on: %i[edit, update, destroy]

  def index;
  end

  def new
    @price = @product.prices.build
  end

  def create
    @price = @product.prices.build price_params
    flash.notice, path = if @price.save
                           ['Add Seller Successful', admin_product_path(@product)]
                         else
                           [@price.errors.messages, new_admin_product_price_path(@product)]
                         end
    redirect_to path
  end

  def edit;
  end

  def update
    flash.notice, path = if @price.update(price_params)
                           ['Add New Price Successful', admin_product_path(@product)]
                         else
                           [@price.errors.messages, edit_admin_product_price_path(@product, @price)]
                         end
    redirect_to path
  end

  def destroy
    flash.notice = if @price.destroy
                     'Delete price successful'
                   else
                     'Delete price failed'
                   end
    redirect_to admin_product_path(@product)
  end

  private

  def product
    @product = Product.find params[:product_id]
  end

  def price
    @price = @product.prices.find params[:id]
  end

  def product_params
    params.permit(:product_id)
  end

  def price_params
    params.require(:price).permit(%i[price seller link])
  end

end

app/helpers/admin/prices_helper.rb
module Admin::PricesHelper
end

app/views/admin/prices/edit.html.erb
<%== form_with model: @price, url: admin_product_price_path(@product, @price), method: :put do |f| %>
  <p>
    <%== f.label :price %>
    <%== f.text_field :price, placeholder: "Add A New Price", value: nil %>
  </p>
  <!--  <p>-->
  <%#= f.label :link %>
  <%#= f.text_field :link %>
  <!--  </p>-->
  <%== f.submit %>
<% end %>

app/views/admin/prices/new.html.erb
<%== form_with model: @price, url: admin_product_prices_path(@product, @price), method: :post do |p| %>
  <p>
    <%== p.label :price %> <br>
    <%== p.text_field :price, placeholder: "Add A New Price" %>
  </p>
  <p>
    <%== p.label :seller %> <br>
    <%== p.text_field :seller, placeholder: "Add A New seller" %>
  </p>
  <p>
    <%== p.label :link %> <br>
    <%== p.text_field :link, placeholder: "Add A New link" %>
  </p>
  <%== p.submit %>
<% end %>