config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  resources :users
  resources :products
  namespace :admin do
    resources :products do
      resources :prices
    end
    resources :brands
    resources :categories
  end

  # post 'admin/products/:id', to: 'admin/products#create'

  get 'admin', to: 'admin#index'

  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#logout'
  get 'permission_restriction', to: 'sessions#permission_restriction'

  get 'admin/login', to: 'admin#login'
  post 'admin/login', to: 'admin#login_auth'
  post 'admin/logout', to: 'admin#logout'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: {minimum: 2}, uniqueness: {scope: :brand_id, message: 'One brand should have one unique product'}
  belongs_to :brand
  belongs_to :category
  has_many :prices, dependent: :destroy

  # belongs_to :brand
  # add_reference :products, :brand
  # t.belongs_to :author
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def index
    @products = Product.all.order(updated_at: :desc)
  end

  def new
    @product = Product.new
    @prices = @product.prices.build
  end

  def create
    @product = Product.new(product_params)
    @price = @product.prices.build(price_params)
    flash.notice, path = if @product.save
                           ['Add Product Successful', :admin_products]
                         else
                           [@product.errors.messages.to_s + @price.errors.messages.to_s, :new_admin_product]
                         end
    redirect_to path
  end

  def edit
    @product = Product.find(params[:id])
    @prices = @product.prices.build
  end

  def update
    @product = Product.find(params[:id])
    flash.notice, path = if @product.update(product_params)
                           ['Change Product Details Successful', :admin_products]
                         else
                           [@product.errors.messages, :edit_admin_product]
                         end
    redirect_to path
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    flash.notice, path = if @product.destroy
                           ['Delete product successful', :admin_products]
                         else
                           [@product.errors.messages, admin_product_path(@product)]
                         end
    redirect_to path
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand_id, :category_id, :types, :detail)
  end

  def origin_price_params
    params.require(:product).permit(price: %i[price seller link])
  end

  def price_params
    {
        seller: origin_price_params[:price][:seller],
        link: origin_price_params[:price][:link],
        price: origin_price_params[:price][:price]
    }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authorized
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%== form_with model: product, url: path, method: method do |f| %>
  <p>
    <%== f.label :name %><br>
    <%== f.text_field :name, placeholder: "Add The Product Name" %>
  </p>
  <p>
    <%== f.label :brand_id %><br>
    <%== f.collection_select :brand_id, Brand.all, :id, :name, prompt: "Pick a Brands" %>
  </p>
  <p>
    <%== f.label :category_id %><br>
    <%== f.collection_select :category_id, Category.all, :id, :name, prompt: "Pick a Category" %>
    <%# <%== f.select(:category_id, @categories.map{|i| [i.name, i.id]}) %>
  </p>
  <p>
    <%== f.label :types %><br>
    <%== f.text_field :types, placeholder: "Add The Product Type" %>
  </p>
  <% if action_name == 'new' %>
    <%== render partial: 'price', locals: {price: @prices, f: f} %>
  <% end %>
  <p>
    <%== f.label :detail %><br>
    <%== f.text_field :detail, placeholder: "Add The Product Details" %>
  </p>
  <%== f.submit %>
  </p>
<% end %>

app/views/admin/products/_price.html.erb
<p>
  <%== f.fields_for price do |p| %>
  <p>
    <%== p.label :price %> <br>
    <%== p.text_field :price, placeholder: "Add A New Price" %>
  </p>
  <p>
    <%== p.label :seller %> <br>
    <%== p.text_field :seller, placeholder: "Add A New seller" %>
  </p>
  <p>
    <%== p.label :link %> <br>
    <%== p.text_field :link, placeholder: "Add A New link" %>
  </p>
<% end %>
</p>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<%== render partial: 'form', locals: {path: :admin_product, product: @product, method: :put} %>

app/views/admin/products/index.html.erb
<p><%== button_to :new_product, :new_admin_product, method: :get %> <%== button_to :new_brand, :new_admin_brand, method: :get %> <%== button_to :new_category, :new_admin_category, method: :get %> </p>
<table>
  <tr>
    <th>Name</th>
    <th>brand</th>
    <th>categories</th>
    <th>types</th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%== link_to product.name, admin_product_path(product) %></td>
      <td><%== product.brand.name %></td>
      <td><%== product.category.name %></td>
      <td><%== product.types %></td>
      <td><%== product.prices.ids %></td>
      <td><%== button_to :edit, edit_admin_product_path(product), method: :get %>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%== render partial: 'form', locals: {path: :admin_products, product: @product, method: :post} %>

app/views/admin/products/show.html.erb
<%== button_to :Add_New_Seller, new_admin_product_price_path(@product), method: :get %>
<%== button_to :Delete_product, admin_product_path(@product), method: :delete %>
<div>
  <p>Name: <%== @product.name %></p>
  <p>Type: <%== @product.types %></p>
  <p>Brand: <%== @product.brand.name %></p>
  <p>Category: <%== @product.category.name %></p>
  <p>Create_at: <%== @product.created_at %></p>
  <p>Update_at: <%== @product.updated_at %></p>
  <p>Detail: <%== @product.detail %></p>
  <table>
    <tr>
      <th>Seller</th>
      <th>Link</th>
      <th>price</th>
    </tr>
    <% @product.prices.each do |p| %>
      <tr>
        <td><%== p.seller %></td>
        <td><%== p.link %></td>
        <td>
          <% p.price.each do |item| %>
            <%== item['updated_at'] %> -> <%== item['price'] %><br>
          <% end %>
        </td>
        <td><%== button_to :Add_New_Price, edit_admin_product_price_path(@product, p), method: :get %></td>
        <td><%== button_to :Delete_Price, admin_product_price_path(@product, p), method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>